(******************************************************************************)
(*                                                                            *)
(*                          RULES OF GO (WEIQI)                               *)
(*                                                                            *)
(*     Formalizing the ancient game: ko and superko rules, seki life,         *)
(*     territory vs area scoring, Japanese and Chinese rule differences,      *)
(*     and komi compensation.                                                 *)
(*                                                                            *)
(*     "The board is a mirror of the mind of the players as the game          *)
(*      progresses."                                                          *)
(*     - Yasunari Kawabata, The Master of Go                                  *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 6, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
